import { Job } from '../types';

const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior React Developer',
    company: 'Microsoft',
    location: 'Redmond, WA',
    skills: ['React', 'TypeScript', 'Redux', 'GraphQL'],
    url: 'https://example.com/job/1',
    isHot: true,
    postedDate: '2 hours ago',
    source: 'LinkedIn',
  },
  {
    id: '2',
    title: 'Software Engineer - Backend',
    company: 'Tata Consultancy Services',
    location: 'Mumbai, MH',
    skills: ['Java', 'Spring Boot', 'Microservices', 'SQL'],
    url: 'https://example.com/job/2',
    isHot: false,
    postedDate: '1 day ago',
    source: 'Naukri',
  },
  {
    id: '3',
    title: 'Frontend Superhero',
    company: 'Stark Industries',
    location: 'New York, NY',
    skills: ['React', 'TypeScript', 'TailwindCSS', 'Vibranium.js'],
    url: 'https://example.com/job/3',
    isHot: true,
    postedDate: '1 day ago',
    source: 'Stark Industries',
  },
  {
    id: '4',
    title: 'Data Scientist',
    company: 'Amazon',
    location: 'Bengaluru, KA',
    skills: ['Python', 'Machine Learning', 'AWS', 'PyTorch'],
    url: 'https://example.com/job/4',
    isHot: false,
    postedDate: '3 days ago',
    source: 'LinkedIn',
  },
  {
    id: '5',
    title: 'Full Stack Ninja',
    company: 'Wayne Enterprises',
    location: 'Gotham City',
    skills: ['Node.js', 'React', 'Stealth', 'MongoDB'],
    url: 'https://example.com/job/5',
    isHot: false,
    postedDate: '3 days ago',
    source: 'Wayne Enterprises',
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'Infosys',
    location: 'Pune, MH',
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    url: 'https://example.com/job/6',
    isHot: true,
    postedDate: '5 hours ago',
    source: 'Naukri',
  },
  {
    id: '7',
    title: 'UI/UX Designer',
    company: 'Google',
    location: 'Hyderabad, TS',
    skills: ['Figma', 'User Research', 'Prototyping', 'Adobe XD'],
    url: 'https://example.com/job/7',
    isHot: false,
    postedDate: '1 week ago',
    source: 'LinkedIn',
  },
  {
    id: '8',
    title: 'Cloud Architect',
    company: 'Asgardian Tech',
    location: 'Asgard',
    skills: ['Azure', 'GCP', 'Terraform', 'Mjolnir'],
    url: 'https://example.com/job/8',
    isHot: true,
    postedDate: '1 hour ago',
    source: 'Asgardian Tech',
  },
  {
    id: '9',
    title: 'QA Automation Engineer',
    company: 'Wipro',
    location: 'Chennai, TN',
    skills: ['Selenium', 'Cypress', 'Java', 'Testing'],
    url: 'https://example.com/job/9',
    isHot: false,
    postedDate: '2 days ago',
    source: 'Naukri',
  },
  {
    id: '10',
    title: 'Product Manager',
    company: 'Salesforce',
    location: 'San Francisco, CA',
    skills: ['Agile', 'Roadmapping', 'Jira', 'Product Strategy'],
    url: 'https://example.com/job/10',
    isHot: true,
    postedDate: 'Just now',
    source: 'LinkedIn',
  },
  {
    id: '11',
    title: 'Mobile Maverick (iOS)',
    company: 'Queen Consolidated',
    location: 'Star City',
    skills: ['Swift', 'Objective-C', 'Archery'],
    url: 'https://example.com/job/11',
    isHot: false,
    postedDate: '5 days ago',
    source: 'Queen Consolidated',
  },
  {
    id: '12',
    title: 'Business Analyst',
    company: 'HCL Technologies',
    location: 'Noida, UP',
    skills: ['SQL', 'Tableau', 'Requirement Gathering'],
    url: 'https://example.com/job/12',
    isHot: false,
    postedDate: '4 days ago',
    source: 'Naukri',
  },
  {
    id: '13',
    title: 'Android Alchemist',
    company: 'S.T.A.R. Labs',
    location: 'Central City',
    skills: ['Kotlin', 'Java', 'Speed Force'],
    url: 'https://example.com/job/13',
    isHot: false,
    postedDate: '1 week ago',
    source: 'S.T.A.R. Labs',
  },
  {
    id: '14',
    title: 'Cyber Security Analyst',
    company: 'PwC',
    location: 'Kolkata, WB',
    skills: ['Penetration Testing', 'Cryptography', 'SIEM'],
    url: 'https://example.com/job/14',
    isHot: false,
    postedDate: '6 days ago',
    source: 'Naukri',
  },
  {
    id: '15',
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    location: 'Remote',
    skills: ['Python', 'TensorFlow', 'NLP', 'Deep Learning'],
    url: 'https://example.com/job/15',
    isHot: true,
    postedDate: '4 hours ago',
    source: 'LinkedIn',
  }
];

export const fetchJobs = (): Promise<Job[]> => {
  return new Promise(resolve => {
    setTimeout(() => {
      // Shuffle the jobs to simulate a live feed
      resolve([...mockJobs].sort(() => Math.random() - 0.5));
    }, 1000);
  });
};